apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-springboot
  template:
    metadata:
      labels:
        app: web-springboot
    spec:
      containers:
        - name: springboot
          image: glocalmind/webspringboot:web0
          ports:
            - containerPort: 8090
          env:
            - name: PORT
              value: "8090"
---
apiVersion: v1
kind: Service
metadata:
  name: demoeks-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: demoeks-springboot